# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c2521497ac1e06d7523140dbd756eabd42655d42bb784d6fd27a646c6a6378e928821196929cf6636042c744e6bcccda8ed352763af84d2480a44b5af8c4aeb

test:
  secret_key_base: 8f52a282c961705dd65467aa667c9b45b6702eddeec092caf950ba38a6751bc5f2c8f87904e388a97f4e5bf42afb1aac97a239b30b51b0b8b79bafdcf966f2e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
